import { createApp } from 'vue';
import App from './App.vue';
import Router from './router';
import axios from 'axios';
import request from './utils/request';
import storage from './utils/storage';
import ElementPlus, { ElMessage } from 'element-plus';
import store from './store';
import config from './config';
import api from './api/index';
import 'element-plus/lib/theme-chalk/index.css';
const app = createApp(App);
app.use(Router);
app.use(store);
app.use(ElementPlus);
app.config.globalProperties.$request = request;
app.config.globalProperties.$api = api;
app.config.globalProperties.$message = ElMessage;

app.config.globalProperties.$storage = storage;
// console.log(import.meta.env);
app.mount('#app');
